=== Entry Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__Entry (abstract)__*

h|*Description*
2+a|The abstract parent of all `Entry` subtypes. An `Entry` is the root of a logical item of  hard  clinical information created in the  clinical statement  context, within a clinical session. There can be numerous such contexts in a clinical session. Observations and other Entry types only ever document information captured/created in the event documented by the enclosing Composition.

An `Entry` is also the minimal unit of information any query should return, since a whole `Entry` (including subparts) records spatial structure, timing information, and contextual information, as well as the subject and generator of the information.

h|*Inherit*
2+|`<<_content_item_class,Content_item>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*time*: `link:/releases/BASE/{base_release}/base.html#_date_time_class[Date_time^]`
a|Effective time at which the information reported in the Entry was true. For specific Entry types, this can be:

* time at which observed result was true;
* time administrative action took place;
* time diagnostic assessment was made.

h|*0..1*
|*other_participations*: `List<link:/releases/BASE/{base_release}/base.html#_participation_class[Participation^]>`
a|Other participations at `Entry` level.

h|*1..1*
|*language*: `link:/releases/BASE/{base_release}/base.html#_terminology_code_class[Terminology_code^]`
a|Mandatory indicator of the localised language in which this Entry is written. Coded from openEHR Code Set  languages .

h|*1..1*
|*subject*: `link:/releases/BASE/{base_release}/base.html#_party_proxy_class[Party_proxy^]`
a|Id of human subject of this `Entry`, e.g.:

* organ donor
* foetus
* a family member
* another clinically relevant person.

h|*0..1*
|*reporter*: `link:/releases/BASE/{base_release}/base.html#_party_proxy_class[Party_proxy^]`
a|Optional identification of reporter of the information in this `Entry`, which might be:

* the patient
* a patient agent, e.g. parent, guardian
* the clinician
* a device or software

Generally only used when the recorder needs to make it explicit. Otherwise, Composition composer and other participants are assumed.

h|*0..1*
|*comment*: `link:/releases/BASE/{base_release}/base.html#_text_class[Text^]`
a|TODO: consider if needed to take comment field from CEM StatementBase

h|*0..1*
|*authorization_actions*: `List<link:/releases/BASE/{base_release}/base.html#_participation_class[Participation^]>`
a|TODO: the openEHR approach treats authorization as being performed on committed data item/document, which is probably more correct.

h|*0..1*
|*lifecycle_state*: `<<_entry_lifecycle_states_enumeration,Entry_lifecycle_states>>`
a|State within Entry lifecycle, if applicable. States defined by the Entry state machine.

Void indicates that no lifcycle is required for this Entry, and that it is regarded as 'completed' when created.

h|*0..1*
|*workflow_id*: `link:/releases/BASE/{base_release}/base.html#_string_class[String^]`
a|Identifier of externally held workflow engine data for this workflow execution, for this subject of care.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*subject_is_self* (): `link:/releases/BASE/{base_release}/base.html#_boolean_class[Boolean^]` +
 +
__Post_condition__: `Result implies subject.generating_type = “PARTY_SELF”`
a|Returns True if this Entry is about the subject of the EHR, in which case the subject attribute is of type PARTY_SELF.

h|*Invariants*
2+a|__Language_valid__: `code_set (Code_set_id_languages).has_code (language)`

h|
2+a|__Encoding_valid__: `code_set (Code_set_id_character_sets).has_code (encoding)`

h|
2+a|__Subject_validity__: `subject_is_self implies subject.generating_type = “PARTY_SELF”`

h|
2+a|__Other_participations_valid__: `other_participations /= Void implies not other_participations.is_empty`

h|
2+a|__Is_archetype_root__: `is_archetype_root`
|===
