=== Composition Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Composition*

h|*Description*
2+a|Content of one version in a `VERSIONED_COMPOSITION`. A Composition is considered the unit of modification of the record, the unit of transmission in record Extracts, and the unit of attestation by authorising clinicians. In this latter sense, it may be considered equivalent to a signed document.

NOTE: It is strongly recommended that the inherited attribute `_uid_` be populated in Compositions, using the UID copied from the `_object_id()_` of the `_uid_` field of the enclosing `VERSION` object. +
For example, the `ORIGINAL_VERSION.uid` `87284370-2D4B-4e3d-A3F3-F303D2F4F34B::uk.nhs.ehr1::2` would be copied to the `_uid_` field of the Composition.

h|*Inherit*
2+|`link:/releases/BASE/{base_release}/base_types.html#_locatable_class[Locatable^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*language*: `link:/releases/BASE/{base_release}/foundation_types.html#_terminology_code_class[Terminology_code^]`
a|Mandatory indicator of the localised language in which this Composition is written. Coded from openEHR Code Set  `languages`. The language of an Entry if different from the Composition is indicated in `Entry._language_`.

h|*1..1*
|*territory*: `link:/releases/BASE/{base_release}/foundation_types.html#_terminology_code_class[Terminology_code^]`
a|Name of territory in which this Composition was written. Coded from openEHR  countries  code set, which is an expression of the ISO 3166 standard.

h|*1..1*
|*category*: `link:/releases/BASE/{base_release}/data_types.html#_coded_text_class[Coded_text^]`
a|Temporal category of this Composition, i.e.

* `431&#124;persistent&#124;` - of potential life-time validity;
* `451&#124;episodic&#124;` - valid over the life of a care episode;
* `433&#124;event&#124;` - valid at the time of recording (long-term validity requires subsequent clinical assessment).

or any other code defined in the openEHR terminology group 'category'.

h|*0..1*
|*context*: `<<_event_context_class,Event_context>>`
a|The clinical session context of this Composition, i.e. the contextual attributes of the clinical session.

h|*1..1*
|*composer*: `link:/releases/BASE/{base_release}/patterns.html#_party_proxy_class[Party_proxy^]`
a|The person primarily responsible for the content of the Composition (but not necessarily its committal into the EHR system). This is the identifier which should appear on the screen. It may or may not be the person who entered the data. When it is the patient, the special self  instance of `PARTY_PROXY` will be used.

TODO: could be renamed to more clearly indicate 'person responsible for the content', usually the legally responsible clinician.

h|*0..1*
|*content*: `List<<<_content_item_class,Content_item>>>`
a|The content of this Composition.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*is_persistent* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if category is `431&#124;persistent&#124;`, False otherwise. Useful for finding Compositions in an EHR which are guaranteed to be of interest to most users.

h|*Invariants*
2+a|__Category_validity__: `terminology (Terminology_id_openehr).has_code_for_group_id (Group_id_composition_category, category.defining_code)`

h|
2+a|__Territory_valid__: `code_set(Code_set_id_countries).has_code(territory)`

h|
2+a|__Language_valid__: `code_set(Code_set_id_languages).has_code(language)`

h|
2+a|__Content_valid__: `content /= Void implies not content.is_empty`

h|
2+a|__Is_archetype_root__: `is_archetype_root`
|===
