=== Order Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Order*

h|*Description*
2+a|Used to specify actions to be performed in the future. Used for any actionable statement such as medication, therapeutic orders, monitoring, recall and review. Sufficient details must be provided for the specification to be directly executable by the intended performer.

The inherited `_time_` field records the point in time at which the order was made (in the real world).

Not to be used for planned activities which are only specified in general terms.

h|*Inherit*
2+|`<<_care_act_entry_class,Care_act_entry>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*narrative*: `link:/releases/S2-RM-BASE/{base_release}/docs/data_types.html#_text_class[Text^]`
a|Mandatory human-readable version of what the Instruction is about.

h|*0..1*
|*expiry_time*: `link:/releases/S2-RM-BASE/{base_release}/docs/foundation_types.html#_date_time_class[Date_time^]`
a|Optional expiry date/time to assist determination of when an Instruction can be assumed to have expired. This helps prevent false listing of Instructions as Active when they clearly must have been terminated in some way or other.

h|*0..1*
|*activities*: `List<<<_activity_class,Activity>>>`
a|List of all activities in Instruction.

h|*Invariants*
2+a|__Activities_valid__: `activities /= Void implies not activities.is_empty`
|===
