=== State_transition Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*State_transition*

h|*Description*
2+a|Model of a transition in the Instruction State Machine, caused by a careflow step. The attributes document the careflow step as well as the ISM transition.

h|*Inherit*
2+|`link:/releases/S2-RM-BASE/{base_release}/docs/patterns.html#_locatable_class[Locatable^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*transition*: `<<_order_execution_transition_enumeration,Order_execution_transition>>`
a|The ISM transition which occurred to arrive in the current_state. Coded by openEHR terminology group  Instruction transitions.

h|*0..1*
|*careflow_step*: `link:/releases/S2-RM-BASE/{base_release}/docs/foundation_types.html#_terminology_term_class[Terminology_term^]`
a|The step in the careflow process which occurred as part of generating this action, e.g.  dispense,  start_administration. This attribute represents the clinical  label for the activity, as  opposed to current_state which represents  the state machine (ISM)  computable form. Defined in archetype.

h|*1..1*
|*current_state*: `<<_order_execution_state_enumeration,Order_execution_state>>`
a|The ISM current state. Coded by openEHR terminology group Instruction states.

h|*0..1*
|*reason*: `List<link:/releases/S2-RM-BASE/{base_release}/docs/data_types.html#_text_class[Text^]>`
a|Optional possibility of adding one or more reasons for this careflow step having been taken. Multiple reasons may occur in medication management for example.

h|*Invariants*
2+a|__Current_state_valid__: `terminology (Terminology_id_openehr).has_code_for_group_id (Group_id_instruction_states, current_state.defining_code)`

h|
2+a|__Transition_valid__: `transition /= Void implies terminology (Terminology_id_openehr).
has_code_for_group_id (Group_id_instruction_transitions, transition.defining_code)`
|===
