=== Activity Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Activity*

h|*Description*
2+a|Defines a single activity within an Instruction, such as a medication administration.

TODO: probably remove possibility of multiple ACTIVITY

h|*Inherit*
2+|`link:/releases/S2-RM-BASE/{base_release}/docs/patterns.html#_locatable_class[Locatable^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*timing*: `link:/releases/S2-RM-BASE/{base_release}/docs/data_types.html#_timing_class[Timing^]`
a|Timing of the activity, in the form of a parsable string. If used, the preferred syntax is ISO8601 'R' format, but other formats may be used including HL7 GTS.

May be omitted if:

* timing is represented structurally in the `_description_` attribute (e.g. via archetyped elements), or
* unavailable, e.g. imported legacy data; in such cases, the `INSTRUCTION._narrative_` should carry text that indicates the timing of its `_activities_`.

TODO - review - current approach is via separate fields in CEMs.

h|*1..1*
|*description*: `List<link:/releases/S2-RM-BASE/{base_release}/docs/patterns.html#_node_class[Node^]>`
a|Description of the activity, in the form of an archetyped structure.

h|*Invariants*
2+a|__Action_archetype_id_valid__: `not action_archetype_id.is_empty`
|===
